### PR TITLE
Updated the Vaadin parts to 2023

### PR DESCRIPTION
**Pull request by mstahv**
Couple of enhancements ideas for Vaadin + one bug discovered as well 👍

### CODE REVIEW

**Comment by fh-ms** [comment]
Hi Matti,
Thanks for your cool contribution!
Working fine, except that the FilterComboBoxes don't update anymore on a filter change. They are supposed to only display the available entries within the current set filter in a view.

**Review by fh-ms — CHANGES_REQUESTED** [review]
Hi Matti,
Thanks for your cool contribution!
Working fine, except that the FilterComboBoxes don't update anymore on a filter change. They are supposed to only display the available entries within the current set filter in a view.

**Comment by mstahv** [comment]
Hi, I think I don't know exactly what you mean. Would you explain what I need to do in the UI to reproduce the issue?

**Comment by fh-ms** [comment]
https://user-images.githubusercontent.com/53050506/218795621-39652c90-42b0-44b4-b54b-b101302b4261.mp4

**Comment by mstahv** [comment]
Got it, thanks! If this is how it is supposed to work, one of my comments is invalid as well. I'll try to fix it somehow...

**Comment by mstahv** [comment]
Now filtering options based on other filters.

**Review by fh-ms — APPROVED** [review]
It's working as intended now.  Thx.

**Comment by mstahv** [comment]
Awesome, Spring Boot 3 + Vaadin 24 update will arrive in couple of weeks 😎

**Pull request merged**
